spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

data-storage:
  upload-path: C://uploads